# Passing Environment Variables at Runtime
env:
    MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
    MAILCHIMP_LIST_ID: ${{ secrets.MAILCHIMP_LIST_ID }}
    MAILCHIMP_SERVER_PREFIX: ${{ secrets.MAILCHIMP_SERVER_PREFIX }}
    NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
    RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
    NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
    ENV_MODE: production

jobs:
    build:
      runs-on: base
      steps:
        - name: Build and Run
          run: |
            docker build --build-arg MAILCHIMP_API_KEY=$MAILCHIMP_API_KEY --build-arg MAILCHIMP_LIST_ID=$MAILCHIMP_LIST_ID --build-arg MAILCHIMP_SERVER_PREFIX=$MAILCHIMP_SERVER_PREFIX --build-arg NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY --build-arg RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY --build-arg NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL --build-arg ENV_MODE=$ENV_MODE -t my-image:latest .
            docker run -e MAILCHIMP_API_KEY=$MAILCHIMP_API_KEY -e MAILCHIMP_LIST_ID=$MAILCHIMP_LIST_ID -e MAILCHIMP_SERVER_PREFIX=$MAILCHIMP_SERVER_PREFIX -e NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY -e RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY -e NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL -e ENV_MODE=$ENV_MODE my-image:latest